langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: trusty
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: ia22Qf1CH5jqsTMIvqEYK8hjnfH9tre2WUUHq3CQivpDb9xixIB+WhIyf52/XH7o4Ue7OCPJRIZeFg5OesoBLNVIClsw81Y2ye/OI8Ldcrm40rnnKYyoj3kkkf+03wv/axcZDsVEC1wFZTkbl9NUR2mhRqfZiQaUvlBO80OM6ERjv2Y37BryoA22eXrJb3fsefFYmv01t3QtfRxcneLmLxNtHufII63t8Dv0Nn9AhRFVwli1y7Y7LeVoeZFsIhLjQ5DMDQcBQr4YR6ia1lNEKG2d4AGDlxwsUDSdRTOG/8qlEZsZjvMtP9ON71j5/QsXy4YIP5vRsT9i1KEDlbA6wDTo3q8Kzuw+NcjJYNKldtEjjwEL9gVDSXMnUnCFXwe58V46Aggj6sDxv3v6GY8pITooD2/+Kf8hQ3ca/oL97UG2rm1/Nd3dkAqhtj8P7onLUduLfhxiXK7vMCtEp2kQ0EgLzpryqSvZuFkM9UOHrNBuuGTdxC3IlBh4hWMotDn29QzcynsKPevFc+UNlkNtixcgAfQtFz0VMYmNZ3sWuWBJ30y1kn1de48fWjl2iUoR5CiXFSaBl16CqGEmwRjxsT2Jr5VoGvbeLqwO0axVMokHC7B99Cb0056Gly4vt0IVE+but6ZqjtqiDGI/fosYP+1tTa04YrJuYRlKWlkWfeE=
  app: 
  run: rails db:migrate
